version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www:/var/www/html
    depends_on:
      - php
    networks:
      - webnet

  php:
    image: php:8.1-fpm
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
    networks:
      - webnet
    build: 
      context: .
      dockerfile: Dockerfile

  mysql:
    image: mysql:8.0 # İstediğiniz MySQL sürümünü kullanabilirsiniz (örneğin mysql:5.7)
    environment:
      MYSQL_ROOT_PASSWORD: 2203Nili01 # Güçlü bir root parolası belirlemelisiniz!
      MYSQL_DATABASE: hmyndb
      MYSQL_USER: humayundb
      MYSQL_PASSWORD: 2203Nili # Güçlü bir kullanıcı parolası belirlemelisiniz!
    volumes:
      - mysql_data:/var/lib/mysql # Veri kalıcılığı için volume tanımlıyoruz
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql # MySQL servisine hostname ile bağlanıyoruz (servis adı: mysql)
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  mysql_data: # MySQL veri volume'u
